name: Fetch latest phishtank intelligence to mysql

on:
  # push:
  #   branches:
  #     - phishtank-python
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fetch_phishtank_intelligence:
    name: Fetch phishtank Intelligence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   ref: phishtank-python

      - name: Check running datetime
        run: echo "Running job on $(date)"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Fetch phishtank Intelligence
        run: python ./src/fetch_phishtank_intelligence.py --host ${{ secrets.MYSQL_HOST }} --user ${{ secrets.MYSQL_USER }} --password ${{ secrets.MYSQL_PASSWORD }} --port ${{ secrets.MYSQL_PORT }} --phishtank_token ${{ secrets.PHISHTANK_TOKEN }}
