on:
  push:
    branches:
      - openphish-python
jobs:
  fetch_openphish_intelligence:
    name: Fetch OpenPhish Intelligence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Fetch OpenPhish Intelligence
        run: python ./src/main.py
      
