on:
  push:
    branches:
      - openphish-python
jobs:
  fetch_openphish_intelligence:
    name: Fetch OpenPhish Intelligence
    runs-on: ubuntu-latest
    
    steps:
      - run: python ./src/utils/phishing_intelligence/fetch_openphish.py
