name: Fetch latest openphish intelligence to mysql

on:
  push:
    branches:
      - openphish-python
jobs:
  fetch_openphish_intelligence:
    name: Fetch OpenPhish Intelligence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check running datetime
        run: echo "Running job on $(date)"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Fetch OpenPhish Intelligence
        run: python ./src/fetch_phishing_intelligence.py --host ${{ secrets.MYSQL_HOST }} --user ${{ secrets.MYSQL_USER }} --password ${{ secrets.MYSQL_PASSWORD }} --port ${{ secrets.MYSQL_PORT }}
